server:
  port: ${PORT:3000}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/readykids}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true
